#!/bin/bash

set -e -u -o pipefail

if grep 'Test[[:lower:]]' *_test.go; then
  echo "Bad test name, it won't be run" >&2
  exit 1
fi

go test
files="$(gofmt -l *.go)"
if [[ -n "${files}" ]]; then
  echo "Badly-formatted files: ${files}" >&2
  echo "Run gofmt on them." >&2
  exit 1
fi
