#!/bin/bash

set -e -u -o pipefail

if grep 'Test[[:lower:]]' ./*_test.go; then
  echo "Bad test name, it won't be run" >&2
  exit 1
fi

files="$(gofmt -l ./*.go)"
if [[ -n "${files}" ]]; then
  echo "Badly-formatted files: ${files}" >&2
  echo "Fix with:" >&2
  echo "$ gofmt -w ${files}" >&2
  exit 1
fi

# Check for missing error handling.
errcheck -blank

# Coverage runs tests, so there's no need to run them separately.
gocover
